language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - yarn && yarn stylelint
  - yarn prettier:fix && yarn prettier:check
  - yarn eslint:check
  - yarn test
branches:
  only:
    - master
